services:
  graphite:
    image: graphiteapp/graphite-statsd
    ports:
      - "8888:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"
    networks:
      - test

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - test

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
    networks:
      - test

  cassandra:
    image: cassandra:3.11.12
    ports:
      - "9042:9042"
      - "9160:9160"
    networks:
      - test

networks:
  test: {}