//
//      Copyright (C) DataStax Inc.
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
//

using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Net;
using System.Threading.Tasks;

using Cassandra.Connections;
using Cassandra.Connections.Control;
using Cassandra.ExecutionProfiles;
using Cassandra.Metrics.Internal;
using Cassandra.Observers.Abstractions;
using Cassandra.Requests;
using Cassandra.Serialization;

namespace Cassandra.SessionManagement
{
    /// <inheritdoc />
    /// <remarks>This is an internal interface designed to declare the internal methods that are called
    /// across multiple locations of the driver's source code.</remarks>
    internal interface IInternalSession : ISession
    {
        /// <summary>
        /// Unique Session ID generated by the driver.
        /// </summary>
        Guid InternalSessionId { get; }

        /// <summary>
        /// Initialize the session
        /// </summary>
        Task Init();

        /// <summary>
        /// Gets or creates the connection pool for a given host
        /// </summary>
        IHostConnectionPool GetOrCreateConnectionPool(Host host, HostDistance distance);

        /// <summary>
        /// Gets a snapshot of the connection pools
        /// </summary>
        IEnumerable<KeyValuePair<IPEndPoint, IHostConnectionPool>> GetPools();

        /// <summary>
        /// Gets the existing connection pool for this host and session or null when it does not exists
        /// </summary>
        IHostConnectionPool GetExistingPool(IPEndPoint address);

        void CheckHealth(Host host, IConnection connection);

        bool HasConnections(Host host);

        void OnAllConnectionClosed(Host host, IHostConnectionPool pool);

        /// <summary>
        /// Gets or sets the keyspace
        /// </summary>
        new string Keyspace { get; set; }
        
        /// <summary>
        /// Fetches the request options that were mapped from the provided execution profile's name.
        /// </summary>
        IRequestOptions GetRequestOptions(string executionProfileName);

        /// <summary>
        /// Returns the number of connected nodes.
        /// </summary>
        int ConnectedNodes { get; }

        IMetricsManager MetricsManager { get; }

        IObserverFactory ObserverFactory { get; }

        /// <summary>
        /// Executes the prepare request on the first host selected by the load balancing policy.
        /// When <see cref="QueryOptions.IsPrepareOnAllHosts"/> is enabled, it prepares on the rest of the hosts in
        /// parallel.
        /// In case the statement was already in the prepared statements cache, logs an warning but prepares it anyway.
        /// </summary>
        Task<PreparedStatement> PrepareInternal(ISerializerManager serializerManager, PrepareRequest request);
        
        /// <summary>
        /// Gets the the prepared statements cache
        /// </summary>
        ConcurrentDictionary<byte[], PreparedStatement> PreparedQueries { get; }

        bool AnyOpenConnections(Host host);
        
        /// <summary>
        /// Helper method to retrieve the aggregate distance from all configured LoadBalancingPolicies and set it at Host level.
        /// </summary>
        HostDistance RetrieveAndSetDistance(Host host);
        
        /// <summary>
        /// Gets the control connection used by the session
        /// </summary>
        IControlConnection GetControlConnection();

        /// <summary>
        /// If contact points are not provided in the builder, the driver will use localhost
        /// as an implicit contact point.
        /// </summary>
        bool ImplicitContactPoint { get; }

        IReadOnlyDictionary<IContactPoint, IEnumerable<IConnectionEndPoint>> GetResolvedEndpoints();
    }
}